supply_per_city_size: 5
production_levels: 5
min_city_distance: 4
space_per_player: 500
move_cost_of_roads: 0.25
orders:
  none:
    type: unit_state_transform
    transform_to: none
  go:
    type: action
  fortify:
    type: unit_state_transform
    transform_to: fortified
  # siege:
  #   type: unit_state_transform
  #   transform_to: siege_mode
  build_city:
    type: construction
    structure: city
  build_road:
    type: construction
    structure: road
  # build_fortress:
  #   type: construction
  #   structure: fortress
  # build_farm:
  #   type: construction
  #   structure: farm
units:
  infantry:
    movement: 
      base: 4
    allowed_orders:
      - none
      - go
      - fortify
      # - siege
  worker:
    movement: 
      base: 2
    allowed_orders:
      - none
      - go
      - build_city
      - build_road
      # - build_fortress
      # - build_farm
  # tank:
  #   movement: 
  #     base: 2
  #     penalty_terrain: 
  #       marsh: null
  #       forest: 4
  #   allowed_orders:
  #     - none
  #     - go
  #     - fortify
      # - siege
  # ship:
  #   movement:
  #     base: 6
  #   allowed_orders:
  #     - none
  #     - go
terrain:
  grass:
    type: land
    move_cost: 1
    fortification_bonus: 2
  plains:
    type: land
    move_cost: 1
    fortification_bonus: 2
  desert:
    type: land
    move_cost: 2
    fortification_bonus: 1.5
  mountains:
    type: land
    move_cost: null
    fortification_bonus: null
  water:
    type: water
    move_cost: 1
    fortification_bonus: null
  # forest:
  #   type: land
  #   move_cost: 2
  #   fortification_bonus: 3
  # marsh:
  #   type: land
  #   move_cost: 2
  #   fortification_bonus: null
  # hill:
  #   type: land
  #   move_cost: 2
  #   fortification_bonus: 2
structures:
  road:
    time_cost: 1
  fortress:
    time_cost: 8
  farm:
    time_cost: 3
  city:
    time_cost: 1